name: NuGet NuGetTemplate - Publish Package

on:
  push:
    branches: [ main ]
    paths:
      - 'libraries/NuGetTemplate/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/_R06.publish-package.yml
    with:
      project: NuGetTemplate
