name: Reusable (R03) - Build Function App

on:
  workflow_call:
    inputs:
      integration-directory:
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  build-functionapp:
    name: Build Function App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Set credentials for GitHub source
        run: |
          dotnet nuget update source github \
            --username "${{ github.repository_owner }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text

      - name: Restore dependencies
        working-directory: ${{ inputs.integration-directory }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.integration-directory }}
        run: dotnet build -c Release --no-restore

      - name: Test
        working-directory: ${{ inputs.integration-directory }}
        run: dotnet test -c Release --no-build

      - name: Publish
        working-directory: ${{ inputs.integration-directory }}/src
        run: dotnet publish -c Release --no-build -o ./publish

      - name: Package function app
        working-directory: ${{ inputs.integration-directory }}/src
        run: |
          cd publish
          zip -r ../../../../functionapp.zip .

      - name: Upload function app artifact
        uses: actions/upload-artifact@v6
        with:
          name: functionapp
          path: functionapp.zip
          if-no-files-found: error
