name: Reusable (R04) - Deploy Function App

on:
  workflow_call:
    inputs:
      functionapp-name:
        required: true
        type: string
    secrets:
      azure-credentials:
        required: true
      azure-resource-group:
        required: true

jobs:
  deploy-functionapp:
    name: Deploy Function App
    runs-on: ubuntu-latest
    steps:
      - name: Download function app artifact
        uses: actions/download-artifact@v7
        with:
          name: functionapp
          path: functionapp

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Deploy To Azure
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.azure-resource-group }} \
            --name ${{ inputs.functionapp-name }} \
            --src functionapp/functionapp.zip
