name: Reusable (R06) - Publish NuGet

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  pack-nuget:
    name: Pack NuGet
    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      PROJECT_DIRECTORY: libraries/${{ inputs.project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          source-url: ${{ env.SOURCE }}

      - name: NuGet auth and restore
        uses: ./.github/actions/nuget-auth-restore
        with:
          working-directory: ${{ env.PROJECT_DIRECTORY }}

      - name: Build
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_DIRECTORY }}/${{ inputs.project }}.csproj -c Release --no-build

      - name: Publish NuGet package
        run: >
          dotnet nuget push **/Release/**/*.nupkg
          --source ${{ env.SOURCE }}
          --api-key ${{ env.NUGET_AUTH_TOKEN }}
          --skip-duplicate
