name: Deploy Shared Infrastructure

on:
  workflow_dispatch:

jobs:
  build-infrastructure:
    name: Build Bicep Infrastructure
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./shared-infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate bicep
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          az bicep install
          az bicep build -f shared.bicep
          az bicep build-params -f shared.bicepparam --outfile parameters.json

      - name: Upload infrastructure artifact
        working-directory: ${{ env.WORKING_DIRECTORY }}
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: ./*.json
          if-no-files-found: error

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [build-infrastructure]
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download infrastructure artifact
        uses: actions/download-artifact@v4
        with:
          name: infra
          path: infra

      - name: Deploy infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infra/shared.json \
            --parameters infra/parameters.json
