name: GoogleDrive - Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'integrations/GoogleDrive/infra/**'
      - 'integrations/GoogleDrive/src/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'integrations/GoogleDrive/infra/**'
      - 'integrations/GoogleDrive/src/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: R05 Build and Deploy Integration
    uses: ./.github/workflows/_R05.deploy-integration.yml
    with:
      infra-directory: ./integrations/GoogleDrive/infra
      integration-directory: ./integrations/GoogleDrive
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      azure-resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
