name: Todoist - Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'integrations/Todoist/infra/**'
      - 'integrations/Todoist/src/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'integrations/Todoist/infra/**'
      - 'integrations/Todoist/src/**'

  workflow_dispatch:

env:
  INTEGRATION_DIRECTORY: ./integrations/Todoist
  INFRA_DIRECTORY: ./integrations/Todoist/infra
  FUNCTION_APP_DIRECTORY: ./integrations/Todoist/src

jobs:
  build-infrastructure:
    name: Build Bicep Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate bicep
        working-directory: ${{ env.INFRA_DIRECTORY }}
        run: |
          az bicep install
          az bicep build -f main.bicep
          az bicep build-params -f main.bicepparam --outfile parameters.json

      - name: Upload infrastructure artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra
          path: ${{ env.INFRA_DIRECTORY }}/*.json
          if-no-files-found: error

  build-functionapp:
    name: Build Function App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        working-directory: ${{ env.INTEGRATION_DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.INTEGRATION_DIRECTORY }}
        run: dotnet build -c Release --no-restore

      - name: Test
        working-directory: ${{ env.INTEGRATION_DIRECTORY }}
        run: dotnet test -c Release --no-build

      - name: Publish
        working-directory: ${{ env.FUNCTION_APP_DIRECTORY }}
        run: dotnet publish -c Release --no-build -o ./publish

      - name: Package function app
        working-directory: ${{ env.FUNCTION_APP_DIRECTORY }}
        run: |
          cd publish
          zip -r ../../../../functionapp.zip .

      - name: Upload function app artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: functionapp.zip
          if-no-files-found: error

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [build-infrastructure, build-functionapp]
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download infrastructure artifact
        uses: actions/download-artifact@v5
        with:
          name: infra
          path: infra

      - name: Deploy infrastructure
        run: |
          deploymentOutput=$(az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infra/main.json \
            --parameters infra/parameters.json \
            --query properties.outputs \
            --output json)

          appName=$(echo $deploymentOutput | jq -r '.appName.value')

          echo "appName=$appName"
          echo "appName=$appName" >> $GITHUB_OUTPUT

  deploy-functionapp:
    name: Deploy Function App
    runs-on: ubuntu-latest
    needs: [build-functionapp, deploy-infrastructure]
    steps:
      - name: Download function app artifact
        uses: actions/download-artifact@v5
        with:
          name: functionapp
          path: functionapp

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy To Azure
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ needs.deploy-infrastructure.outputs.appName }} \
            --src functionapp/functionapp.zip
